git:
  depth: 1
language: go
go:
  - 1.5.2
install:
  - go get -v github.com/spf13/hugo
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install gulp -g
script:
  - gulp deploy --debug
