# Build directories
publishdir: _dist
archetypedir: src/archetype
layoutdir: src/templates
contentdir: src/content
dataDir: src/data
staticdir: src/files

# Hugo settings
buildDrafts: false
buildFuture: false
relativeURLs: true
canonifyURLs: false
permalinks:
  posts: blog/:title/

# Site metadata
baseURL: ""
languageCode: en-gb
title: Foley
