# Build directories
publishdir: _dist
archetypedir: src/archetype
layoutdir: src/templates
contentdir: src/content
dataDir: src/data
staticdir: src/files

# Hugo settings
canonifyurls: true
permalinks:
  posts: blog/:title/

# Site metadata
baseurl: http://testurl.dev
languageCode: en-gb
title: Foley
